services:
  - type: web
    name: dev-blogs-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      # Add other environment variables as needed
